import { readFile, stat } from "node:fs/promises";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceFiles = [
  "src/index.js",
  "src/audio/audio-manager.js",
  "src/assets/save-store.js",
  "src/core/exi-engine.js",
  "src/core/animation.js",
  "src/core/camera.js",
  "src/core/collision.js",
  "src/core/graphics.js",
  "src/core/math.js",
  "src/core/pathfinding.js",
  "src/core/node.js",
  "src/core/render-group.js",
  "src/core/particle-emitter.js",
  "src/core/profiler.js",
  "src/core/sprite.js",
  "src/core/nine-slice-sprite.js",
  "src/core/text.js",
  "src/core/animated-sprite.js",
  "src/core/input.js",
  "src/core/sprite-batch.js",
  "src/core/tilemap.js",
  "src/assets/texture.js",
  "src/assets/render-texture.js",
  "src/assets/texture-atlas.js",
  "src/assets/ktx2.js",
  "src/assets/asset-loader.js",
  "src/render/batch.js",
  "src/render/post-process.js",
  "src/render/scissor.js",
  "src/render/webgl2-renderer.js",
  "src/render/webgpu-renderer.js",
  "src/render/clear.js",
  "src/render/instanced.js",
  "tools/exi-mcp-server.mjs",
];

for (const relativePath of sourceFiles) {
  const source = await readFile(path.join(root, relativePath), "utf8");
  assert.doesNotMatch(source, /from\s+["'](?:pixi|phaser|three|babylon|godot|bevy)/i, `${relativePath} harici motor import ediyor`);
  assert.doesNotMatch(source, /\beval\s*\(|\bnew\s+Function\s*\(/, `${relativePath} dinamik kod çalıştırıyor`);
}

const engine = await readFile(path.join(root, "src/core/exi-engine.js"), "utf8");
assert.match(engine, /WebGL2Renderer/);
assert.match(engine, /WebGPURenderer/);
assert.match(engine, /fallbackToWebGL/);
assert.match(engine, /dispatchPointerInput/);
assert.match(engine, /pointerHoverTargetFor/);
assert.match(engine, /runtime-error/);
assert.match(engine, /handlePageHide/);
assert.match(engine, /handlePageShow/);
const assetLoader = await readFile(path.join(root, "src/assets/asset-loader.js"), "utf8");
assert.match(assetLoader, /readImageDimensions/);
assert.match(assetLoader, /waitForAbort/);
assert.match(await readFile(path.join(root, "src/core/node.js"), "utf8"), /setPointerHandlers/);
const index = await readFile(path.join(root, "src/index.js"), "utf8");
assert.match(index, /AnimatedSprite/);
assert.match(index, /SpriteBatch/);
assert.match(index, /NineSliceSprite/);
assert.match(index, /Text/);
assert.match(index, /TextCache/);
assert.match(index, /GlyphAtlas/);
assert.match(index, /RenderTexture/);
assert.match(index, /RenderGroup/);
assert.match(index, /findGridPath/);
assert.match(await readFile(path.join(root, "src/core/pathfinding.js"), "utf8"), /MAX_GRID_PATH_CELLS/);

const server = await readFile(path.join(root, "server.mjs"), "utf8");
assert.match(server, /startsWith\(`\$\{root\}\$\{path\.sep\}`\)/);
assert.match(server, /Content-Security-Policy/);
assert.match(server, /realpath/);
assert.match(server, /"\.png": "image\/png"/);
assert.match(server, /"\.mp3": "audio\/mpeg"/);
assert.match(server, /"\.ktx2": "image\/ktx2"/);
assert.match(server, /function isPublicFile/);
assert.match(server, /blockedFileNames/);
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
assert.deepEqual(packageJson.dependencies || {}, {});
assert.equal(typeof packageJson.scripts?.doctor, "string");
assert.equal(typeof packageJson.scripts?.check, "string");
assert.equal(typeof packageJson.scripts?.mcp, "string");
assert.equal(typeof packageJson.scripts?.["test:mcp"], "string");
assert.equal(typeof packageJson.scripts?.["test:unit"], "string");
assert.equal(typeof packageJson.scripts?.lint, "string");
assert.equal(typeof packageJson.scripts?.["test:typecheck"], "string");
assert.equal(typeof packageJson.scripts?.["test:coverage"], "string");
assert.equal(typeof packageJson.scripts?.["bench:regression"], "string");
assert.match(packageJson.scripts.test, /run-all\.mjs/);
for (const agentFile of ["AI_ENGINE_GUIDE.md", "AGENTS.md", "CLAUDE.md", "GEMINI.md", "CONTRIBUTING.md", "API.md", "MCP.md"]) {
  const agentGuide = await readFile(path.join(root, agentFile), "utf8");
  assert.ok(agentGuide.length > 0, `${agentFile} boş olmamalı`);
}
assert.match(await readFile(path.join(root, "AI_ENGINE_GUIDE.md"), "utf8"), /npm run doctor/);
assert.match(await readFile(path.join(root, "AI_ENGINE_GUIDE.md"), "utf8"), /exi_api/);
assert.match(await readFile(path.join(root, "AI_ENGINE_GUIDE.md"), "utf8"), /\$callback/);
const mcpGuide = await readFile(path.join(root, "MCP.md"), "utf8");
assert.match(mcpGuide, /node tools\/exi-mcp-server\.mjs/);
assert.match(mcpGuide, /npm run mcp.*stdout/s);
assert.match(mcpGuide, /\$callback/);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /AssetLoader/);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /exi_preview_start/);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /tools\/call.*tek kuyrukta/s);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /annotations/);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /exi:\/\/runtime/);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /exi:\/\/clients/);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /exi_file_check/);
assert.match(await readFile(path.join(root, "API.md"), "utf8"), /prompts\/get/);
const apiDoc = await readFile(path.join(root, "API.md"), "utf8");
assert.match(apiDoc, /callRoutes/);
assert.match(apiDoc, /methodRoutes/);
assert.match(apiDoc, /resources, callRoutes/);
assert.match(apiDoc, /\$callback/);
assert.match(apiDoc, /inspect.*callbacks/);
assert.doesNotMatch(apiDoc, /\| `exi_export_call` \|.*Texture\.fromImage/);
for (const toolName of ["exi_api", "exi_create", "exi_function", "exi_export_get", "exi_export_call", "exi_static_call", "exi_call", "exi_inspect", "exi_get", "exi_set", "exi_release", "exi_session_reset", "exi_build_scene", "exi_scaffold", "exi_project_apply", "exi_project_open", "exi_file_list", "exi_file_read", "exi_file_write", "exi_file_patch", "exi_file_begin", "exi_file_chunk", "exi_file_commit", "exi_file_abort", "exi_asset_list", "exi_asset_read", "exi_asset_write", "exi_asset_begin", "exi_asset_chunk", "exi_asset_commit", "exi_asset_abort", "exi_file_check", "exi_project_check", "exi_check", "exi_preview_start", "exi_preview_call", "exi_preview_batch", "exi_preview_probe", "exi_preview_stop", "exi_batch"]) assert.match(apiDoc, new RegExp(`\\\`${toolName}\\\``));
const mcpServer = await readFile(path.join(root, "tools/exi-mcp-server.mjs"), "utf8");
assert.match(mcpServer, /resources\/list/);
assert.match(mcpServer, /await getPublicMethod/);
assert.match(mcpServer, /exi_preview_start/);
assert.match(mcpServer, /exi_preview_call/);
assert.match(mcpServer, /exi_preview_batch/);
assert.match(mcpServer, /runtimeCallbacks/);
assert.match(mcpServer, /\$callback/);
assert.match(mcpServer, /runtime-command/);
assert.match(mcpServer, /exi:\/\/runtime/);
assert.match(mcpServer, /exi:\/\/clients/);
assert.match(mcpServer, /clientContract/);
assert.doesNotMatch(mcpServer, /opencode2/);
assert.match(mcpServer, /prompts\/list/);
assert.match(mcpServer, /prompts\/get/);
assert.match(mcpServer, /exi_create_game/);
assert.match(mcpServer, /exi_verify_runtime/);
assert.match(mcpServer, /exi_batch/);
assert.match(mcpServer, /calls 1 ile 128/);
assert.match(mcpServer, /resolveBatchReferences/);
assert.match(mcpServer, /function resolveBatchResultPath/);
assert.match(mcpServer, /function isClass/);
assert.match(mcpServer, /function apiContract/);
assert.match(mcpServer, /methodRoutes/);
assert.match(mcpServer, /const MODERN_PROTOCOL_VERSION = "2026-07-28"/);
assert.match(mcpServer, /server\/discover/);
assert.match(mcpServer, /function requestEra/);
assert.match(mcpServer, /resultType: "complete"/);
assert.match(mcpServer, /io\.modelcontextprotocol\/clientCapabilities/);
assert.match(mcpServer, /Object\.getOwnPropertyDescriptor\(exported, property\)/);
assert.match(mcpServer, /Object\.getOwnPropertyDescriptor\(value, name\)/);
assert.match(mcpServer, /function resolveBytes/);
assert.match(mcpServer, /function resolveArgs/);
assert.match(mcpServer, /function inspectHandle/);
assert.match(mcpServer, /function getPublicStaticMethod/);
assert.match(mcpServer, /MAX_BINARY_BYTES/);
assert.match(mcpServer, /MAX_BASE64_STRING_LENGTH/);
assert.match(mcpServer, /MAX_CHUNKED_ASSET_BYTES/);
assert.match(mcpServer, /MAX_PENDING_ASSET_BYTES/);
assert.match(mcpServer, /MAX_PROJECT_CHECK_ERROR_BYTES/);
const runtimeAgent = await readFile(path.join(root, "src", "ai", "runtime-agent.js"), "utf8");
assert.match(runtimeAgent, /class RuntimeAgent/);
assert.match(runtimeAgent, /createCanvasObserver/);
assert.match(runtimeAgent, /createEngineObserver/);
assert.match(runtimeAgent, /canvas-grid/);
assert.match(runtimeAgent, /registerCallback/);
assert.match(runtimeAgent, /MAX_CALLBACKS/);
assert.match(runtimeAgent, /\$callback/);
assert.match(runtimeAgent, /this\.callbacks\.keys/);
assert.doesNotMatch(runtimeAgent, /eval\s*\(|new Function\s*\(/);
assert.match(mcpServer, /const MAX_PREVIEW_STARTUP_MS = 10_000/);
assert.match(mcpServer, /MAX_RUNTIME_TELEMETRY_BYTES/);
assert.match(mcpServer, /const timeoutMs = \{ doctor: 60_000, test: 180_000, verify: 300_000 \}\[mode\]/);
assert.match(mcpServer, /assertSafeScaffoldTarget/);
assert.match(mcpServer, /function openProject/);
assert.match(mcpServer, /function terminateProcessTree/);
assert.match(mcpServer, /notifications\/cancelled/);
assert.match(mcpServer, /activeRequests/);
assert.match(mcpServer, /function cancellationError/);
assert.match(mcpServer, /function sendProgress/);
assert.match(mcpServer, /notifications\/progress/);
assert.match(mcpServer, /function readProjectFile/);
assert.match(mcpServer, /function listProjectFiles/);
assert.match(mcpServer, /function readProjectAsset/);
assert.match(mcpServer, /function writeProjectFile/);
assert.match(mcpServer, /function beginProjectFileUpload/);
assert.match(mcpServer, /function writeProjectFileChunk/);
assert.match(mcpServer, /function commitProjectFileUpload/);
assert.match(mcpServer, /function replaceUploadedFile/);
assert.match(mcpServer, /function writeProjectTarget/);
assert.match(mcpServer, /function abortProjectFileUpload/);
assert.match(mcpServer, /MAX_CHUNKED_PROJECT_FILE_BYTES/);
assert.match(mcpServer, /MAX_PENDING_PROJECT_FILE_BYTES/);
assert.match(mcpServer, /MAX_PROJECT_FILE_CHUNK_BYTES/);
assert.match(mcpServer, /function listProjectAssets/);
assert.match(mcpServer, /function writeProjectAsset/);
assert.match(mcpServer, /function beginAssetUpload/);
assert.match(mcpServer, /function writeAssetChunk/);
assert.match(mcpServer, /function commitAssetUpload/);
assert.match(mcpServer, /function abortAssetUpload/);
assert.match(mcpServer, /function checkProjectFile/);
assert.match(mcpServer, /function checkProject/);
assert.match(mcpServer, /function checkHTMLReferences/);
assert.match(mcpServer, /function ensureProjectParent/);
assert.match(mcpServer, /function assertProjectJSONBudget/);
assert.match(mcpServer, /if \(!Object\.hasOwn\(message, "id"\)\) return/);
assert.match(mcpServer, /projectFileExtensions/);
assert.match(mcpServer, /scaffoldDirectories/);
assert.match(mcpServer, /requireScaffoldFile/);
assert.match(mcpServer, /lstat/);
assert.match(mcpServer, /SIGTERM/);
assert.match(mcpServer, /taskkill\.exe/);
assert.match(mcpServer, /windowsHide: true/);
assert.match(mcpServer, /let toolQueue = Promise\.resolve\(\)/);
assert.match(mcpServer, /EXI_MCP_OUTPUT_LIMIT/);
assert.match(mcpServer, /target !== Object\.prototype/);
assert.match(mcpServer, /if \(value === undefined\) return null/);
assert.match(mcpServer, /readOnlyHint/);
assert.match(mcpServer, /destructiveHint/);
assert.doesNotMatch(mcpServer, /console\.log\s*\(/);
const types = await readFile(path.join(root, "index.d.ts"), "utf8");
const demo = await readFile(path.join(root, "src/demo.js"), "utf8");
const demoHtml = await readFile(path.join(root, "index.html"), "utf8");
assert.match(demo, /runtimeNode\.dataset/);
assert.match(demo, /RuntimeAgent/);
assert.match(demo, /createEngineObserver/);
assert.match(demo, /__exi\/runtime-token/);
assert.match(demo, /runtimeCallbacks/);
assert.match(demo, /window\.game/);
assert.match(demoHtml, /id="exi-runtime"/);
const webgpuRenderer = await readFile(path.join(root, "src/render/webgpu-renderer.js"), "utf8");
const webglRenderer = await readFile(path.join(root, "src/render/webgl2-renderer.js"), "utf8");
const engineSource = await readFile(path.join(root, "src/core/exi-engine.js"), "utf8");
assert.match(engineSource, /captureFrame/);
assert.match(webglRenderer, /readRenderTarget/);
assert.match(webgpuRenderer, /readRenderTarget/);
assert.match(webgpuRenderer, /COPY_SRC/);
const hardwareSoak = await readFile(path.join(root, "test/hardware-soak.mjs"), "utf8");
assert.match(types, /subtract\(value: Vec2\)/);
assert.match(types, /multiplyScalar\(value: number\)/);
assert.match(types, /line\(x1: number, y1: number, x2: number, y2: number, width\?: number/);
assert.match(types, /fixedStep\?: number; maxFrameDelta\?: number/);
assert.match(types, /timeScale\?: number/);
assert.match(types, /interpolate\?: boolean/);
assert.match(types, /pauseOnHidden\?: boolean/);
assert.match(types, /pause\(\): this/);
assert.match(types, /resume\(\): this/);
assert.match(types, /setTimeScale\(value: number\): this/);
assert.match(types, /suspend\(\): Promise<void>/);
assert.match(types, /resume\(\): Promise<void>/);
assert.match(types, /pauseAudio\?: boolean/);
assert.match(types, /pauseAudio: boolean/);
assert.match(types, /suspendAudio\(\): this/);
assert.match(types, /resumeAudio\(\): this/);
assert.match(types, /animator\?: Animator \| null/);
assert.match(types, /animator: Animator \| null/);
assert.match(types, /constructor\(options\?: \{ maxTweens\?: number \}\)/);
assert.match(types, /maxTweens: number; tweens: Set<Tween>/);
assert.match(types, /remove\(tween: Tween\): boolean/);
assert.match(types, /fromGrid\(texture: Texture/);
assert.match(types, /static pack\(entries: AtlasPackEntry/);
assert.match(types, /type AtlasPackSource = CanvasImageSource \| Texture/);
assert.match(types, /getFrames\(names: readonly string\[\]\)/);
assert.match(types, /getClip\(names: readonly string\[\]/);
assert.match(types, /class TextureAtlas[\s\S]*destroy\(\): void/);
assert.match(types, /updateSource\(source: CanvasImageSource\)/);
assert.match(types, /class RenderTexture extends Texture/);
assert.match(types, /interface RenderGroupOptions/);
assert.match(types, /class RenderGroup extends Node/);
assert.match(types, /target: RenderTexture/);
assert.match(types, /offscreenRoot\?: boolean/);
assert.match(types, /PostProcessEffect/);
assert.match(await readFile(path.join(root, "src/render/post-process.js"), "utf8"), /renderGroupWithPostProcess/);
assert.match(types, /resize\(width: number, height: number\): this/);
assert.match(types, /export type ResizeMode = "resize" \| "contain" \| "cover"/);
assert.match(types, /resizeMode\?: ResizeMode/);
assert.match(types, /setResizeMode\(mode: ResizeMode\): this/);
assert.match(types, /setLogicalSize\(width: number, height: number\): this/);
assert.match(types, /resize\(\): this/);
assert.match(types, /loadKTX2\(url: string/);
assert.match(types, /inspectKTX2\(bytes: Uint8Array/);
assert.match(types, /interface KTX2Info/);
assert.match(types, /KTX2Decoder/);
assert.match(types, /type\?: "texture" \| "json" \| "bytes" \| "ktx2"/);
assert.match(types, /setScreenViewport\(x: number, y: number, width: number, height: number\): this/);
assert.match(types, /roundPixels\?: boolean/);
assert.match(types, /setRoundPixels\(value: boolean\): this/);
assert.match(types, /type\?: "texture" \| "json" \| "bytes" \| "ktx2" \| "atlas"/);
assert.match(types, /isScreenPointInViewport\(x: number, y: number\): boolean/);
assert.match(types, /renderToTexture\(target: RenderTexture/);
assert.match(types, /setFilter\(filter: "linear" \| "nearest"\)/);
assert.match(types, /maxTexturePixels\?: number/);
assert.match(types, /release\(url: string\): boolean/);
assert.match(types, /prepare\(\): \{ batches: number; uploads: number \}/);
assert.match(types, /setScene\(scene: Scene, camera\?: Camera\): this/);
assert.match(types, /overlayScene\?: Scene \| null/);
assert.match(types, /overlayCamera\?: Camera \| null/);
assert.match(types, /setOverlay\(scene: Scene \| null, camera\?: Camera \| null\): this/);
assert.match(types, /focusable\?: boolean/);
assert.match(types, /tabIndex\?: number/);
assert.match(types, /interface NodeLayout/);
assert.match(types, /onUpdate\?: NodeUpdateHandler \| null/);
assert.match(types, /setUpdateHandler\(handler\?: NodeUpdateHandler \| null\)/);
assert.match(types, /setLayout\(layout: NodeLayout \| null\): this/);
assert.match(types, /class NineSliceSprite extends Sprite/);
assert.match(types, /flipX\?: boolean; flipY\?: boolean/);
assert.match(types, /setFlip\(flipX: boolean, flipY\?: boolean\): this/);
assert.match(types, /pingPong\?: boolean/);
assert.match(types, /onLoop\?:/);
assert.match(types, /onFrameChange\?:/);
assert.match(types, /interface TileMapTileOptions/);
assert.match(types, /setTile\(x: number, y: number, tileIndex: number, options\?: TileMapTileOptions\): this/);
assert.match(types, /NineSliceSpriteOptions/);
assert.match(types, /focusNext\(reverse\?: boolean\): boolean/);
assert.match(types, /onKeyDown\?: KeyDownHandler \| null/);
assert.match(await readFile(path.join(root, "src/core/node.js"), "utf8"), /collectFocusables/);
assert.match(await readFile(path.join(root, "src/core/node.js"), "utf8"), /setUpdateHandler/);
assert.match(await readFile(path.join(root, "src/core/input.js"), "utf8"), /onKeyDown/);
assert.match(await readFile(path.join(root, "src/render/webgl2-renderer.js"), "utf8"), /accumulateMetrics = false/);
assert.match(webgpuRenderer, /loadOp: clear \? "clear" : "load"/);
assert.match(types, /shake\(amplitude\?: number, duration\?: number/);
assert.match(types, /InputAxisBinding/);
assert.match(types, /bindAxis\(name: string/);
assert.match(types, /getBindings\(\): \{ actions: InputActionMap; axes: InputAxisMap \}/);
assert.match(types, /setBindings\(bindings\?: \{ actions\?: InputActionMap \| null; axes\?: InputAxisMap \| null \}\)/);
assert.match(types, /setBusMuted\(name: string, muted\?: boolean\): this/);
assert.match(types, /isBusMuted\(name: string\): boolean/);
assert.match(types, /fadeBus\(name: string, volume: number, duration\?: number\): this/);
assert.match(types, /interface AudioProgress/);
assert.match(types, /interface AudioLoadOptions/);
assert.match(types, /interface AudioEntry/);
assert.match(types, /loadMany\(entries: ReadonlyArray<AudioEntry>/);
assert.match(types, /inputAxes\?: InputAxisMap/);
assert.match(types, /onGamepadConnected\?: GamepadHandler/);
assert.match(types, /wasGamepadButtonPressed\(index: number, button: number\)/);
assert.match(types, /interface GamepadRumbleOptions/);
assert.match(types, /rumbleGamepad\(index\?: number, options\?: GamepadRumbleOptions\): Promise<boolean>/);
assert.match(types, /maxWidth\?: number; wordWrap\?: boolean/);
assert.match(types, /deadzoneWidth\?: number; deadzoneHeight\?: number/);
assert.match(await readFile(path.join(root, "src/core/input.js"), "utf8"), /onGamepadDisconnected/);
assert.match(types, /init\(\): Promise<this>/);
assert.match(types, /step\(delta: number\): this/);
assert.match(types, /version: number; destroyed: boolean/);
assert.match(types, /staticCache\?: boolean/);
assert.match(types, /chunkSize\?: number/);
assert.match(types, /spatialCulling\?: boolean/);
assert.match(types, /instanced\?: boolean/);
assert.match(types, /gpuCulling\?: boolean/);
assert.match(types, /ParticleEmitterOptions[\s\S]*gpuCulling\?: boolean/);
assert.match(types, /cullTiles\?: boolean/);
assert.match(types, /setRegion\(x: number, y: number, width: number, height: number/);
assert.match(types, /blendMode\?: BlendMode/);
assert.match(types, /setBlendMode\(mode: BlendMode\)/);
assert.match(types, /containsPoint\(worldX: number, worldY: number\)/);
assert.match(types, /pick\(worldX: number, worldY: number/);
assert.match(types, /pickPointer\(predicate\?: \(\(node: Node\) => boolean\) \| null, pointerId\?: number \| null\)/);
assert.match(types, /interactive\?: boolean/);
assert.match(types, /hitArea\?: ClipRect \| null/);
assert.match(types, /setHitArea\(rect: ClipRect \| null\)/);
assert.match(types, /cullBounds\?: ClipRect \| null/);
assert.match(types, /setCullBounds\(rect: ClipRect \| null\)/);
assert.match(types, /alpha\?: number/);
assert.match(types, /worldAlpha: number/);
assert.match(types, /setAlpha\(value: number\)/);
assert.match(types, /updateWorldMatrix\([\s\S]*parentAlpha\?: number/);
assert.match(types, /FilterKind = "none"/);
assert.match(types, /FilterKind = .*sepia.*contrast.*saturate/);
assert.match(types, /filterAmount\?: number/);
assert.match(types, /setFilter\(filter: FilterKind/);
assert.match(types, /maskRect\?: ClipRect \| null/);
assert.match(types, /setMaskRect\(rect: ClipRect \| null\)/);
assert.match(types, /maskTexture\?: Texture \| null/);
assert.match(types, /setMaskTexture\(texture: Texture \| null\)/);
assert.match(await readFile(path.join(root, "src/core/node.js"), "utf8"), /maskRect/);
assert.match(await readFile(path.join(root, "src/core/node.js"), "utf8"), /maskTexture/);
assert.match(await readFile(path.join(root, "src/render/webgl2-renderer.js"), "utf8"), /u_filter/);
assert.match(await readFile(path.join(root, "src/render/webgl2-renderer.js"), "utf8"), /u_mask/);
assert.match(webgpuRenderer, /filterLayout/);
assert.match(webgpuRenderer, /maskTexture/);
assert.match(types, /raycast\(origin: Point, direction: Point/);
assert.match(types, /interface RaycastHit/);
assert.match(types, /class PhysicsBody/);
assert.match(types, /interface ColliderBounds/);
assert.match(types, /OneWayDirection = "up"/);
assert.match(types, /oneWay\?: OneWayDirection \| null/);
assert.match(types, /kinematic\?: boolean/);
assert.match(types, /isKinematic: boolean/);
assert.match(types, /setKinematic\(value: boolean\): this/);
assert.match(types, /bounds\?: ColliderBounds \| null/);
assert.match(types, /setBounds\(bounds\?: ColliderBounds \| null\)/);
assert.match(types, /class PhysicsWorld/);
assert.match(types, /onBeginContact: PhysicsContactHandler \| null/);
assert.match(types, /onStayContact: PhysicsContactHandler \| null/);
assert.match(types, /onEndContact: PhysicsContactHandler \| null/);
assert.match(types, /interface PhysicsContact/);
assert.match(types, /contact: PhysicsContact/);
assert.match(types, /onBeginContact\?: PhysicsContactHandler/);
assert.match(types, /onStayContact\?: PhysicsContactHandler/);
assert.match(types, /physics\?: PhysicsWorld \| null/);
assert.match(types, /physics: PhysicsWorld \| null/);
assert.match(types, /overlaps\(body: PhysicsBody/);
assert.match(types, /layer\?: number/);
assert.match(types, /mask\?: number/);
assert.match(hardwareSoak, /const createdEngine = await ExiEngine\.create/);
assert.match(hardwareSoak, /maskTextureTested/);
assert.match(hardwareSoak, /postProcessPasses/);
assert.match(hardwareSoak, /token !== runToken \|\| completed/);
assert.match(hardwareSoak, /new RenderTexture/);
assert.match(hardwareSoak, /renderToTexture\(renderTarget/);
assert.match(hardwareSoak, /renderTargetResizes/);
assert.match(hardwareSoak, /inputAxisTested/);
assert.match(hardwareSoak, /cameraShakeTested/);
assert.match(hardwareSoak, /lifecycleTested/);
assert.match(hardwareSoak, /pageLifecycleTested/);
assert.match(hardwareSoak, /timeScaleTested/);
assert.match(hardwareSoak, /interpolateTested/);
assert.match(hardwareSoak, /interpolate: true/);
assert.match(hardwareSoak, /overlayScene/);
assert.match(hardwareSoak, /layoutTested/);
assert.match(hardwareSoak, /focusTested/);
assert.match(hardwareSoak, /nineSliceTested/);
assert.match(types, /onPointerCancel\?: PointerHandler/);
assert.match(types, /onPointerEnter\?: PointerHandler/);
assert.match(types, /onWheel\?: PointerHandler/);
assert.match(types, /currentTarget: Node \| null/);
assert.match(types, /stopPropagation\(\): void/);
assert.match(types, /preventDefault\(\): void/);
assert.match(types, /type: "pointerdown"[\s\S]*\| "wheel"/);
assert.match(types, /wasPointerCancelled\(button\?: number\)/);
assert.match(types, /wasPointerMoved\(\)/);
assert.match(types, /interface PointerState \{[\s\S]*button: number/);
assert.match(types, /class Text extends Sprite/);
assert.match(types, /class TextCache/);
assert.match(types, /class GlyphAtlas/);
assert.match(types, /glyphAtlas\?: GlyphAtlas \| null/);
assert.match(types, /maxPixelRatio\?: number/);
assert.match(types, /maxTextureBytes\?: number/);
assert.match(types, /maxTextureCount\?: number/);
assert.match(types, /pixelRatio: number/);
assert.match(types, /setPixelRatio\(value: number\)/);
assert.match(types, /backgroundColor\?: number \| string/);
assert.match(types, /clearBeforeRender\?: boolean/);
assert.match(types, /activePointerId: number \| null/);
assert.match(types, /readonly destroyed: boolean/);
assert.match(types, /getPointers\(\): ReadonlyMap/);
assert.match(types, /getPointerWorld\(camera: Camera, out\?: Point, pointerId\?: number \| null\)/);
assert.match(types, /follow\(target: Point/);
assert.match(types, /clearFollow\(\): this/);
assert.match(types, /setBounds\(bounds: ClipRect/);
assert.match(types, /zoomAt\(screenX: number, screenY: number, zoom: number\)/);
assert.match(types, /markDirty\(\): this/);
assert.match(types, /addSprites\(options\?: SpriteBatchSpriteOptions\[\]\): this/);
assert.match(types, /addAnimatedSprite\(options: SpriteBatchAnimatedSpriteOptions\): number/);
assert.match(types, /setSpriteAnimation\(index: number, options\?: SpriteBatchAnimationOptions \| null\): boolean/);
assert.match(await readFile(path.join(root, "src/core/sprite-batch.js"), "utf8"), /updateAnimations\(delta\)/);
assert.match(types, /maxJSONBytes\?: number/);
assert.match(types, /maxJSONNodes\?: number/);
assert.match(types, /maxJSONDepth\?: number/);
assert.match(types, /loadJSON<T = unknown>\(url: string, options\?: AssetLoadOptions\): Promise<T>/);
assert.match(types, /autoSync\?: boolean/);
assert.match(types, /gravityY\?: number; autoSync\?: boolean/);
assert.match(types, /createStaticBodies\(physicsWorld: PhysicsWorld/);
assert.match(types, /getCollisionRects\(solidTiles\?/);
assert.match(webgpuRenderer, /dispatchWorkgroups/);
assert.match(webgpuRenderer, /drawIndirect/);
assert.match(webgpuRenderer, /frameValues/);
assert.match(webgpuRenderer, /gpuCullParams/);
assert.match(webgpuRenderer, /cameraPosition: vec2f/);
assert.match(webgpuRenderer, /instancedPipelines/);
assert.doesNotMatch(webgpuRenderer, /const gpuResources = new Map/);
assert.equal((webgpuRenderer.match(/this\.metrics =/g) || []).length, 1);
assert.equal((await readFile(path.join(root, "src/render/webgl2-renderer.js"), "utf8")).match(/this\.metrics =/g)?.length, 1);
assert.doesNotMatch(webgpuRenderer, /queue\.batches\.filter\(/);
const collision = await readFile(path.join(root, "src/core/collision.js"), "utf8");
assert.doesNotMatch(collision, /\$\{cellX\}:\$\{cellY\}/);
assert.doesNotMatch(collision, /const visit = \(collider\) =>/);
const spriteBatch = await readFile(path.join(root, "src/core/sprite-batch.js"), "utf8");
assert.doesNotMatch(spriteBatch, /\$\{cellX\}:\$\{cellY\}/);
assert.match(spriteBatch, /column = this\.spatialIndex\.get\(cellX\)/);
const scissor = await readFile(path.join(root, "src/render/scissor.js"), "utf8");
assert.match(scissor, /output = null/);
assert.match(webgpuRenderer, /getScissorRect\(batch\.clip, renderWidth, renderHeight, this\.scissorRect\)/);
assert.match(webgpuRenderer, /ensureRenderTarget\(target\)/);
assert.match(webgpuRenderer, /EXI_RENDER_TARGET_INPUT/);
assert.match(webgpuRenderer, /EXI_RENDER_INPUT/);
assert.match(await readFile(path.join(root, "src/render/webgl2-renderer.js"), "utf8"), /framebufferTexture2D/);
assert.match(await readFile(path.join(root, "src/render/webgl2-renderer.js"), "utf8"), /getScissorRect\(batch\.clip, renderWidth, renderHeight, this\.scissorRect\)/);
assert.match(types, /radToDeg\(radians: number\): number/);
assert.match(types, /getVisibleBounds\(out\?: ClipRect\): ClipRect/);
assert.match(types, /getVector\(xAxisName: string, yAxisName: string/);
assert.match(types, /traverse\(callback: \(node: Node\) => void\): void/);
assert.match(types, /find\(predicate: \(node: Node\) => boolean\): Node \| null/);
assert.match(types, /findByName\(name: string\): Node \| null/);
assert.match(types, /roundedRect\(x: number, y: number, width: number, height: number/);
assert.doesNotMatch(types, /\n  sub\(value: Vec2\)/);
assert.doesNotMatch(types, /\n  scale\(value: number\)/);
// Test altyapısı varlık kontrolleri (AAA kalite araç zinciri)
for (const requiredFile of ["test/run-all.mjs", "tools/lint.mjs", "test/typecheck-syntax.mjs", "test/fixtures/typecheck.ts", "test/coverage/coverage.mjs", "test/coverage/thresholds.mjs", "test/benchmark/benchmark-regression.mjs", "test/e2e/preview-e2e.mjs", ".github/workflows/ci.yml"]) {
  const info = await stat(path.join(root, requiredFile));
  assert.ok(info.size > 0, `${requiredFile} boş olmamalı`);
}
const guide = await readFile(path.join(root, "AI_ENGINE_GUIDE.md"), "utf8");
assert.match(guide, /npm run lint/);
assert.match(guide, /npm run test:coverage/);
assert.match(guide, /test\/run-all\.mjs/);
assert.match(guide, /unit suite coverage/);
assert.match(guide, /webgl2 %75\+/);
assert.match(guide, /Node 22\+24/);
const readme = await readFile(path.join(root, "README.md"), "utf8");
assert.match(readme, /\.github\/workflows\/ci\.yml/);
assert.match(readme, /npm run test:coverage/);
console.log("ExiEngine static smoke: passed");
