export const INSTANCE_FLOATS = 14;
export const INSTANCE_STRIDE = INSTANCE_FLOATS * Float32Array.BYTES_PER_ELEMENT;
export const INSTANCE_VERTEX_COUNT = 6;
export const GPU_SOURCE_FLOATS = 16;
export const GPU_SOURCE_STRIDE = GPU_SOURCE_FLOATS * Float32Array.BYTES_PER_ELEMENT;
